version: 0.1.0
type: command
name: training
display_name: Training an AI model
description: Trains an AI model by inputting a lot of training and testing data.

code: ./code
environment: azureml:aml-Tensorflow:0.1.0
command: 'python train.py
  --training_folder ${{inputs.training_folder}} --testing_data ${{inputs.testing_folder}}
  --output_folder ${{outputs.output_folder}}
  --epochs ${{inputs.epochs}}
  '
compute: local

inputs:
  epochs:
    optional: false
    type: number
  testing_folder:
    optional: false
    type: uri_folder
  training_folder:
    optional: false
    type: uri_folder
outputs:
  output_folder:
    type: uri_folder
