name: Azure ML Job Pipeline

on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

env:
  GROUP: mlops
  WORKSPACE: mlops-nathan
  LOCATION: westeurope

jobs:
  azure-pipeline:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # AZURE_CREDENTIALS should be a secret in your repo containing a JSON string of your service principal details

    - name: Execute Azure ML script
      uses: azure/CLI@v1
      id: azure-ml-pipeline
      with:
        azcliversion: 2.53.0
        inlineScript: |
          az extension add --name ml -y
          az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
          az ml job create --file ./pipelines/animals-classification.yaml --set name=animals-classification-${{ github.sha }}-${{ github.run_id }}
          VERSION=$(az ml model -n animal-classification --query "[0].version" -o tsv)
          echo "Latest version of model animal-classification is: $VERSION"
          echo "::set-output name=latest_version::$VERSION"

    - name: Download model
      uses: azure/CLI@v1
      with:
        azcliversion: 2.53.0
        inlineScript: |
          az extension add --name ml -y
          az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
          az ml model download --name animal-classification --download-path ./model --version ${{ steps.azure-ml-pipeline.outputs.latest_version }}"
    
          
