name: Azure ML Job Pipeline Manual
on: 
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GROUP: mlops-at-home
  WORKSPACE: mlops-nathan
  LOCATION: westeurope

permissions:
  id-token: write
  contents: read

jobs:
  azure-pipeline:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure test - Get Compute
        uses: Azure/CLI@v2.0.0
        with:
          azcliversion: 2.53.0 # Best to specify for reproducibility
          inlineScript: |
            az extension add --name ml --debug
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION --debug
            az ml compute list --debug
