name: Azure ML Job Pipeline Manual
on: workflow_dispatch

env:
  GROUP: mlops-at-home
  WORKSPACE: mlops-nathan
  LOCATION: westeurope

jobs:
  azure-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Azure test - Get Compute
        uses: Azure/CLI@v2
        with:
          azcliversion: 2.61.0 # Currently the latest, but best to specify for reproducibility
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
            az ml compute list