name: Azure ML Job Pipeline Manual
on: workflow_dispatch

env:
  GROUP: mlops-at-home
  WORKSPACE: mlops-nathan
  LOCATION: westeurope

permissions:
  id-token: write
  contents: read

jobs:
  azure-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Azure test - Get Compute
        uses: Azure/CLI@v2
        with:
          azcliversion: 2.61.0 # Currently the latest, but best to specify for reproducibility
          inlineScript: |
            az extension add --name ml -y
            az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION --debug
            az ml compute list --debug