name: Small test
on:
    workflow_dispatch:

env:
    GROUP: mlops-at-home
    WORKSPACE: mlops-nathan
    LOCATION: westeurope

permissions:
    id-token: write
    contents: read

jobs:
    azure-pipeline:
        runs-on: ubuntu-24.04
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Azure -- Create Compute
              uses: Azure/CLI@v2.1.0
              with:
                  azcliversion: 2.64.0
                  inlineScript: |
                      az extension add --name ml
                      az configure --defaults group=$GROUP workspace=$WORKSPACE location=$LOCATION
                      az ml compute list --out table