name: Test Local Runner

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  default-job-test:
    runs-on: self-hosted

    steps:
      - name: Test
        run: docker run nathansegers/mlops-animals-api -p 8001:8000